name: latex-build
description: Build a LaTeX Document
author: Ondrej Sika
runs:
  using: docker
  image: docker://schickling/latex
  args:
    - pdflatex
    - ${{ inputs.filename }}
inputs:
  filename:
    required: true
    description: Filename of your LaTeX source





